#!/usr/bin/env bash

# # # # # # #
# author:  Bas Huis
# github:  https://github.com/bas080/bash-tap
# created: Mon Mar  2 20:08:39 CET 2020
# license: GNU General Public License 3.0
# # # #

# Only set runtime parameters when running in Bash. (Dash compatibility)
[ ! -z ${BASH_VERSION:-} ] && {
  # This makes pipelines fail. A sensible default if you ask me.
  set -o pipefail
}

trap '[ ! -z ${NOT_OK:-} ] && exit 1' 0

plan() {
  printf '1..%s\n' "$1"
}

diagnostics() {
  xargs -d '\n' printf '# %s\n'
}

skip() {
  ok "# skip $@"
}

skip_all() {
  printf '1..0 # skip %s\n' "$1"
}

todo() {
  printf 'not ok - # TODO %b\n' "$@"
}

bail() {
  printf 'Bail out! %s\n' "$1"
}

test_success() {
  test $? -eq 0 \
    && ok "$@" \
    || not_ok "$@"
}

test_failure() {
  test $? -ne 0
  test_success "$@"
}

ok() {
  printf 'ok - %b\n' "$1"
}

not_ok() {
  NOT_OK=1
  printf 'not %b\n' "$(ok "$@")"
}

# aliases

success() { test_success "$@"; }
failure() { test_failure "$@"; }
