#!/usr/bin/env bash

# author:  Bas Huis
# website: https://github.com/bas080
# created: Fri Mar 13 02:36:04 CET 2020
# changed: Mon Mar  2 22:19:26 CET 2020
# license: GNU General Public License 3.0

# Only set runtime parameters when running in Bash. (Dash compatibility)
[ ! -z "${BASH_VERSION:-}" ] && {
  # This makes pipelines fail. A sensible default if you ask me.
  set -o pipefail
}

trap on_exit EXIT

on_exit() {
  [ ! -z "${NOT_OK:-}" ] && exit 1
}

plan() {
  if [ -z "${1:-}" ]; then
    plan "$TEST_COUNT"
  else
    printf '1..%s\n' "$1"
  fi
}

diagnostics() {
  xargs -d '\n' printf '# %s\n'
}

skip() {
  ok "# skip $1"
}

skip_all() {
  printf '1..0 # skip %s\n' "$1"
}

todo() {
  printf 'not ok - # TODO %b\n' "$@"
}

bail() {
  printf 'Bail out! %s\n' "$1"
}

test_success() {
  # shellcheck disable=SC2181
  if [ $? -eq 0 ]; then
    ok "$@"
  else
    not_ok "$@"
  fi
}

test_failure() {
  test $? -ne 0
  test_success "$@"
}

ok() {
  TEST_COUNT=$((TEST_COUNT+1))

  # shellcheck disable=SC2059
  printf 'ok - %s\n' "$(printf "$@")"
}

not_ok() {
  NOT_OK=1
  printf 'not %s' "$(ok "$@")"
}

# aliases

success() { test_success "$@"; }
failure() { test_failure "$@"; }
